# --- Database Init SQL ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pm25-db-init
  namespace: jenkins
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS favorites (
        id SERIAL PRIMARY KEY,
        station_name TEXT NOT NULL,
        pm25_value NUMERIC,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO favorites (station_name, pm25_value) VALUES ('Bangkok Startup Station', 25.5);
---
# --- Backend ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm25-backend
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rubchek/pm25-backend:latest
        envFrom:
        - secretRef:
            name: pm25-secrets # ใช้ Secret ตัวที่สร้างไว้แล้ว
---
# --- Frontend ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm25-frontend
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rubchek/pm25-frontend:latest
---
# --- Database (PostgreSQL) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm25-db
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pm25-secrets
              key: DB_PASSWORD    # ดึงค่ารหัสผ่านจาก Secret
        - name: POSTGRES_USER
          value: "user"           # ตรงตามที่บอสกำหนด
        - name: POSTGRES_DB
          value: "mydatabase"     # ตรงตามที่บอสกำหนด
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: db-init
        configMap:
          name: pm25-db-init
          items:
          - key: init.sql
            path: init.sql
---
# --- Prometheus ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm25-prometheus
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
---
# --- Services backend ---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: jenkins
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# --- Services frontend ---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: jenkins
spec:
  type: NodePort       
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 30080 
---
# --- Services database ---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: jenkins
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432