apiVersion: v1
kind: ConfigMap
metadata:
  name: pm25-db-init
  namespace: jenkins
data:
  init.sql: |
    DROP TABLE IF EXISTS favorites;
    CREATE TABLE IF NOT EXISTS favorites (
      id SERIAL PRIMARY KEY,
      station_id TEXT,
      station_name TEXT NOT NULL,
      pm25_value NUMERIC,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
