apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm25-grafana
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana:11.1.0
        envFrom:
        - secretRef:
            name: grafana-secrets
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources-vol
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-datasources-vol
        configMap:
          name: grafana-datasources
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc