---
- name: Configure PM2.5 Monitor Environment
  hosts: webservers
  become: yes # ใช้สิทธิ์ Root (sudo)
  vars:
    is_container: "{{ ansible_virtualization_type in ['docker', 'containerd'] }}"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install system dependencies
      apt:
        name:
          - curl
          - wget
          - git
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: not is_container

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      when: not is_container

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
      when: not is_container

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
      when: not is_container

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      when: not is_container

    - name: Ensure specific environment folders exist
      file:
        path: /opt/pm25-monitor
        state: directory
        mode: '0755'